Ext.define('App.model.SalesOrder', {
    extend: 'Ext.data.Model',
    requires: ['Ext.data.proxy.OData', 'Ext.data.reader.Xml', 'App.api.Error'],
    config: {
        fields: [
            'id',
		{
			name:'SalesOrderID',
			type:'string'
		},
		{
			name:'SalesOrderKey',
			type:'string'
		},
		{
			name:'CreatedByEmployeeLastName',
			type:'string'
		},
		{
			name:'Status',
			type:'string'
		},
		{
			name:'ChangedByEmployeeLastName',
			type:'string'
		},
		{
			name:'ChangedByEmployeeUserID',
			type:'string'
		},
		{
			name:'NetSum',
			type:'float'
		},
		{
			name:'CustomerKey',
			type:'string'
		},
		{
			name:'CreatedByEmployeeUserID',
			type:'string'
		},
		{
			name:'DeliveryStatus',
			type:'string'
		},
		{
			name:'CurrencyCodeDescription',
			type:'string'
		},
		{
			name:'StatusDescription',
			type:'string'
		},
		{
			name:'ChangedByCustomerName',
			type:'string'
		},
		{
			name:'CreatedByEmployeeFirstName',
			type:'string'
		},
		{
			name:'DeliveryStatusDescription',
			type:'string'
		},
		{
			name:'Note',
			type:'string'
		},
		{
			name:'CreatedAt',
            type: 'date',
            dateFormat: 'c'			
		},
		{
			name:'Tax',
			type:'float',
		},
		{
			name:'TotalSum',
			type:'float'
		},
		{
			name:'CreatedByCustomerName',
			type:'string'
		},
		{
			name:'ChangedByEmployeeFirstName',
			type:'string'
		},
		{
			name:'ChangedAt',
            type: 'date',
            dateFormat: 'c'	
		},
		{
			name:'CustomerID',
			type:'string'
		},
		{
			name:'CustomerName',
			type:'string'
		},
		{
			name:'BillingStatus',
			type:'string'
		},
		{
			name:'BillingStatusDescription',
			type:'string'
		},
		{
			name:'Currency',
			type:'string'
		}
		]
    }
});
	